export const Categories = [
  { name: "Apartment", emoji: "🏠", fileName: "apartment" },
  { name: "At the Doctor", emoji: "🩺", fileName: "at-the-doctor" },
  { name: "Body Parts", emoji: "🦵🖐️", fileName: "body-parts" },
  { name: "Daily Activities", emoji: "📅", fileName: "daily-activites" },
  { name: "Deserts", emoji: "🏜️", fileName: "deserts" },
  { name: "Directions", emoji: "🧭", fileName: "directions" },
  { name: "Drinks", emoji: "🥤", fileName: "drinks" },
  { name: "Emergency", emoji: "🚨", fileName: "emergency" },
  { name: "Emotions", emoji: "😊", fileName: "emotions" },
  { name: "Family", emoji: "👨‍👩‍👧‍👦", fileName: "family" },
  { name: "Feeling Unwell", emoji: "🤒", fileName: "feeling-unwell" },
  { name: "Feeling Phrases", emoji: "💬", fileName: "feelingPhrases" },
  { name: "Food Basic", emoji: "🍔", fileName: "food-basic" },
  { name: "Furniture", emoji: "🛋️", fileName: "furniture" },
  { name: "Greetings", emoji: "👋", fileName: "greetings" },
  { name: "Hobbies", emoji: "🎨", fileName: "hobbies" },
  { name: "Hotel", emoji: "🏨", fileName: "hotel" },
  { name: "Kitchen", emoji: "🍳", fileName: "kitchen" },
  { name: "Office", emoji: "🏢", fileName: "office" },
  { name: "Office Activities", emoji: "🗂️", fileName: "ofice-activites" },
  {
    name: "Professional Roles",
    emoji: "💼",
    fileName: "professional-roles",
  },
  { name: "Qualities", emoji: "⭐", fileName: "qualities" },
  { name: "School", emoji: "🏫", fileName: "school" },
  {
    name: "Technology and Devices",
    emoji: "💻",
    fileName: "technology-and-devices",
  },
  { name: "Time and Date", emoji: "⏰", fileName: "time-and-date" },
  { name: "Time Frequency", emoji: "🕰️", fileName: "time-frequency" },
  { name: "Top 30 Adverbs", emoji: "📝", fileName: "top-30-adverbs" },
  {
    name: "Top 40 Adjectives",
    emoji: "🎨",
    fileName: "top-40-adjectives",
  },
  { name: "Top 50 Verbs", emoji: "🏃", fileName: "top-50-verbs" },
  { name: "Transport", emoji: "🚗", fileName: "transport" },
  { name: "Travel", emoji: "✈️", fileName: "travel" },
  { name: "University", emoji: "🎓", fileName: "university" },
  { name: "Weather", emoji: "🌤️", fileName: "weather" },
];
